---
driver:
  name: vagrant

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-2012r2
    driver_config:
      box: opentable/win-2012r2-standard-amd64-nocm

suites:
  - name: ad
    run_list:
      - recipe[sp_lab_build::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
